=== WladimirSidorenko/DASA/data/SB10k/test/gold/scheme/relations.dtd
<!-- DTD for Description of Rhethorical Structure Relations -->
<!-- Created by Uladzimir Sidarenka <sidarenk@uni-potsdam.de> -->

<!-- Relations -->
<!ELEMENT relations (relations+)>

<!ATTLIST relations
	scheme	CDATA	#REQUIRED>

<!-- Relation -->
<!ENTITY % reltype "(par|hyp)">
<!ELEMENT relation (description,nucleus?,satellite?,nucsat?,effect?,connectives?,example?,comment?)>
<!ATTLIST relation
	  name	CDATA	#REQUIRED
	  type	(%reltype) #REQUIRED>

<!-- Relation Description -->
<!ELEMENT description (#PCDATA)>
<!ELEMENT nucleus (#PCDATA)>
<!ELEMENT satellite (#PCDATA)>
<!ELEMENT nucsat (#PCDATA)>
<!ELEMENT effect (#PCDATA)>
<!ELEMENT connectives (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT comment (#PCDATA)>

=== WladimirSidorenko/DASA/data/SB10k/test/gold/scheme/R-PCC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relations SYSTEM "relations.dtd">

<relations>
  <relation name="r-Circumstance" type="hyp">
    <description>
    </description>
    <satellite>A (non-hypothetical) state of affairs.
    </satellite>
    <nucsat>S sets a framework in the subject matter within which R is
    intended to interpret N.
    </nucsat>
    <effect>R recognizes that S provides the framework for
    interpreting N.
    </effect>
    <connectives>when; while; ...; wenn; w&auml;hrend; ... for temporal
    circum- stantials
    </connectives>
    <example>[Als die Veag wegen der Liberalisierung des Strommarktes
    unter Druck geriet,]S [hielt sie sich bei ihren Lieferanten
    schadlos.]N (maz-5297)
    </example>
  </relation>

  <relation name="r-Condition" type="hyp">
    <description>
    </description>
    <satellite>A hypothetical, future, or otherwise unrealized
    situation (relative to the situational context of S).
    </satellite>
    <nucsat>Realization of N depends on realization of S.
    </nucsat>
    <effect>R recognizes how the realization of N depends on the
    realization of S.
    </effect>
    <connectives>if .. then; ... / wenn .. dann; sofern; ...
    </connectives>
    <comment>
    </comment>
  </relation>

  <relation name="r-Otherwise" type="hyp">
    <description>
    </description>
    <nucleus>A hypothetical, future or in some other way unrealized
    state of affairs.
    </nucleus>
    <satellite>A hypothetical, future or in some other way unrealized
    state of affairs.
    </satellite>
    <nucsat>The realization of N prevents realization of S.
    </nucsat>
    <effect>R recognizes the dependency relation of prevention between
    the realization of N and the realization of S.
    </effect>
    <connectives>otherwise; ... / ehe; bevor; sonst; ...
    </connectives>
  </relation>

  <relation name="r-Unless" type="hyp">
    <description>
    </description>
    <nucleus>A hypothetical, future or in some other way unrealized
    state of affairs.
    </nucleus>
    <satellite>A hypothetical, future or in some other way unrealized
    state of affairs.
    </satellite>
    <nucsat>S affects the realization of N; N is realized provided
    that S is not realized.
    </nucsat>
    <effect>R recognizes that N is realized provided that S is not realized.
    </effect>
    <connectives>unless; ... / es sei denn; ...
    </connectives>
    <example>[Morgen wird der Satellit in den Pazifik st&uuml;rzen.]N [Es
    sei denn, er vergl&uuml;ht doch noch vollst&auml;ndig in der
    Erdatmosph&auml;re.]S
    </example>
  </relation>

  <relation name="r-Elaboration" type="hyp">
    <description>
    </description>
    <nucsat>S presents additional detail about the situation (not
    about an individual entity – cf. E-Elaboration below) that is
    presented in N or inferentially accessible in N. Some typical
    relations between N and S are abstraction–instance,
    event–subevent.
    </nucsat>
    <effect>R recognizes S as providing additional detail for N.
    </effect>
    <connectives>in particular; for example; ... / besonders;
    beispielsweise; ...
    </connectives>
    <example>[Diepensee siedelt um.]N [Ohne Wenn und Aber.]S
    (maz-6993)
    </example>
  </relation>

  <relation name="r-E-Elaboration" type="hyp">
    <description>
    </description>
    <nucsat>S presents additional detail about an entity mentioned in
    N. N precedes S in the text. Some typical relations between N and
    S are set–member and whole–part.
    </nucsat>
    <effect>R recognizes S as providing additional detail about an
    entity mentioned in N.
    </effect>
    <connectives>(rarely marked by connectives)
    </connectives>
    <example>[Heute wollen Tausende das Flair eines historischen
    Klassenzimmers kennen lernen,]N [wie sie nur noch wenige in
    Deutschland existieren.]S (maz-6728)
    </example>
    <comment>In the example, the wie minor clause (S) does not relate
    to the whole event of acquainting but only to the class room,
    i.e., an entity within N. .
    </comment>
  </relation>

  <relation name="r-Interpretation" type="hyp">
    <description>
    </description>
    <nucsat>S relates N to a framework of ideas not involved in N
    itself and not concerned with W’s positive regard; or at least,
    positive regard is not the important point. In the text, N
    precedes S.
    </nucsat>
    <effect>R recognizes the interpreting function of S for N.
    </effect>
    <connectives>thus; ... / so; damit; mithin; ...
    </connectives>
    <example>[In Potsdam findet heute der große Festzug zu Ehren von
    Friedrich II. statt.]N [Damit sind die diesj&auml;hrigen
    “Preußen-Tage” beendet.]S
    </example>
    <comment>If the main point of S is to assess N on a scale, the
    suitable relation is not Interpretation but
    Evaluation-N/Evaluation-S.
    </comment>
  </relation>

  <relation name="r-Means" type="hyp">
    <description>
    </description>
    <nucleus>An activity.
    </nucleus>
    <nucsat>S presents a method or instrument which tends to make
    realization of N more likely.
    </nucsat>
    <effect>R recognizes that the method or instrument in S tends to
    make realization of N more likely.
    </effect>
    <connectives>to this end; ... / dazu; damit; ...
    </connectives>
  </relation>

  <relation name="r-Cause" type="hyp">
    <description>
    </description>
    <nucleus>A state of affairs holding in the world. This state has
    been caused by the situation presented in S.
    </nucleus>
    <satellite>A state of affairs holding in the world.
    </satellite>
    <nucsat>The state of affairs in N is being caused by the state of
    affairs in S.
    </nucsat>
    <effect>R recognizes the causal relationship between the two
    states of affairs.
    </effect>
    <connectives>because; since; ... / weil; da; deshalb; ...
    </connectives>
    <example>Unerwartete Pressemeldung zur Verlegung des Ortes
    Diepensee. [&uuml;berrascht reagierte auch B&uuml;rgermeister Jochen
    Wagner.]N [Schließlich gaben die Stadtverord- neten erst
    Montagabend gr&uuml;nes Licht f&uuml;r die weitere Erschließung des neuen
    Ortsteils Diepensee.]S (maz-6993)
    </example>
  </relation>

  <relation name="r-Result" type="hyp">
    <description>
    </description>
    <nucleus>A state of affairs holding in the world. This state
    provides the reason for the situation presented in S.
    </nucleus>
    <satellite>A state of affairs holding in the world.
    </satellite>
    <nucsat>The state of affairs in S is being caused by the state of
    affairs in N.
    </nucsat>
    <effect>R recognizes the causal relationship between the two
    states of affairs.
    </effect>
    <connectives>because; since; ... / weil; da; deshalb; ...
    </connectives>
    <comment>Dual of Cause. The choice between Cause and Result is
    made solely on the grounds of relative importance for the tweet.
    </comment>
  </relation>

  <relation name="r-Purpose" type="hyp">
    <description>
    </description>
    <nucleus>An activity.
    </nucleus>
    <satellite>A hypothetical, future or in some other way unrealized
    state of affairs. This state is expected to be achieved after the
    activity described in N is fulfilled.
    </satellite>
    <nucsat>S is to be realized through the activity in N.
    </nucsat>
    <effect>R recognizes that the activity in N is initiated in order
    to realize S.
    </effect>
    <connectives>by means of; in order to; ... / durch; um .. zu; ...
    </connectives>
    <example>[Um ihre Soldaten zu sch&uuml;tzen,]S [&auml;ußern sich die USA
    nicht zu Berichten &uuml;ber den Beginn der Boden-Operation in
    Afghanistan.]N (maz-5701)
    </example>
    <comment>There is, in a wide sense, a causal relation between S
    and N. The difference to the relations Cause/Result is that for
    Purpose, S is an unrealized state of affairs that is the intention
    of the actor.
    </comment>
  </relation>

  <relation name="r-Solutionhood" type="hyp">
    <description>
    </description>
    <satellite>S presents a problem.
    </satellite>
    <nucsat>N is a solution to the problem presented in S. In the
    text, S usually precedes N.
    </nucsat>
    <effect>R recognizes N as a solution to the problem presented in S
    </effect>
    <connectives>(rarely marked by connectives)
    </connectives>
    <example>[Mit der Verabschiedung des Nichtraucherschutzgesetzes
    sitzen viele Kneipen in der Falle.]S [Es empfiehlt sich, fr&uuml;h
    genug auf die Einrichtung abtrennbarer R&auml;ume zu achten.]N
    </example>
  </relation>

  <relation name="r-Contrast" type="par">
    <description>
    </description>
    <nucleus>No more than two nuclei; the situations in these two
    nuclei are (a) comprehended as the same in many respects (b)
    comprehended as differing in a few respects and (c) compared with
    respect to one or more of these differences.
    </nucleus>
    <effect>R recognizes the comparability and the difference(s)
    yielded by the compar- ison is being made.
    </effect>
    <connectives>on the other hand; but; while; ... / demgegen&uuml;ber;
    hingegen; w&auml;hrend; aber; ...
    </connectives>
    <example>[Mein erstes Auto war ein Kleinwagen.]N [Das zweite
    hingegen ein aus- gewachsener Kombi.]N
    </example>
  </relation>

  <relation name="r-Sequence" type="par">
    <description>
    </description>
    <nucleus>The nuclei describe states of affairs in the world that
    take place in a temporal order.
    </nucleus>
    <effect>R recognizes the temporal succession relationships among
    the nuclei..
    </effect>
    <connectives>then; afterwards; before; ... / dann; anschließend;
    und; zuvor, ...
    </connectives>
    <example>[Um neun betrat die Lehrerin den Klassenraum.]N [F&uuml;nf
    Minuten sp&auml;ter verk&uuml;ndete sie, dass ein Test geschrieben wird.]N
    </example>
